### ISSUE TITLE
Build From Source Errors

### ISSUE THREAD

**Issue by lineagech** [DebashisGanguly/gpgpu-sim_UVMSmart#2]
I am not using Docker but just build from source. My environment is CentOS 6.10, and gcc 5.4 also cuda 8.0. When running benchmarks, it will have the errors at src/option_parser.cc:102 because the argument **str** is an empty string and the type of **m_variable** is integer and an exception happens. The cause is from src/gpgpu-sim/gpu-sim.cc:171. So that I change the 6th parameter from "" to "0". Recompile and then running the benchmark is ok now.

**Comment by DebashisGanguly** [comment]
Please follow the steps mentioned inside Dockerfile as is and religiously. 
The docker image by default set the environment for you.
I have tested with Ubuntu 16.04 and CUDA 8.
So, if you follow the steps in Dockerfile, it will setup the same environment in bare metal.

I am not sure about CentOS and the environment you are testing with. It kind of becomes unpredictable.

If you could configure your node with the setup and then are able to run the benchmark, please close the ticket. Otherwise if you face any issues let me know.

**Comment by lineagech** [comment]
Recompile and then running the benchmark is ok now.
